In [12]:
import pandas as pd
import pickle

In [18]:
with open('go_terms.pkl', 'rb') as f:
    id_to_name = pickle.load(f)
    
# id_to_name

In [19]:
df_cell = pd.read_pickle('cellcom_significant.pkl')
df_cell_table = df_cell[['GO', 'effect_size', 'adj_pvalue']]
GO_names = []
for _, row in df_cell_table.iterrows():
    name = id_to_name[row['GO']]
    GO_names.append(name)
    
df_cell_table['Name'] = GO_names
df_cell_table = df_cell_table[['GO', 'Name', 'effect_size', 'adj_pvalue']]
df_cell_table

/var/folders/1f/m8_t8g414dz2d33zlncf3gv40000gn/T/ipykernel_27406/1428178218.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cell_table['Name'] = GO_names

            GO                              Name  effect_size    adj_pvalue
0   GO:0000785                         chromatin     0.196030  1.961675e-52
1   GO:0005667   transcription regulator complex     0.162793  8.093276e-08
2   GO:0016607                     nuclear speck     0.147233  2.076055e-10
3   GO:0016604                      nuclear body     0.140939  3.369164e-08
4   GO:0005634                           nucleus     0.128876  4.112308e-64
..         ...                               ...          ...           ...
56  GO:0016323       basolateral plasma membrane    -0.181051  1.054487e-12
57  GO:0005764                          lysosome    -0.195273  2.076055e-10
58  GO:0009897  external side of plasma membrane    -0.227091  6.518762e-22
59  GO:0005743      mitochondrial inner membrane    -0.252800  6.267498e-22
60  GO:0005759              mitochondrial matrix    -0.308705  1.620572e-36

[61 rows x 4 columns]

In [21]:
df_cell_table.to_excel('CellCom.xlsx')

In [8]:
df_cell['adj_pvalue'].describe()

count    6.100000e+01
mean     6.684480e-03
std      1.237492e-02
min      4.112308e-64
25%      1.103627e-11
50%      1.338083e-05
75%      8.188533e-03
max      4.928246e-02
Name: adj_pvalue, dtype: float64

In [24]:
df_molfunc = pd.read_pickle('molfunc_significant.pkl')
df_molfunc_table = df_molfunc[['GO', 'effect_size', 'adj_pvalue']]
GO_names = []
for _, row in df_molfunc_table.iterrows():
    name = id_to_name[row['GO']]
    GO_names.append(name)
    
df_molfunc_table['Name'] = GO_names
df_molfunc_table = df_molfunc_table[['GO', 'Name', 'effect_size', 'adj_pvalue']]
df_molfunc_table.to_excel('Molfunc.xlsx')
df_molfunc_table

/var/folders/1f/m8_t8g414dz2d33zlncf3gv40000gn/T/ipykernel_27406/1764414687.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_molfunc_table['Name'] = GO_names

,GO,Name,effect_size,adj_pvalue
0,GO:0001227,"DNA-binding transcription repressor activity, ...",0.303954,7.128310e-34
1,GO:0000978,RNA polymerase II cis-regulatory region sequen...,0.287124,1.043773e-104
2,GO:0000981,"DNA-binding transcription factor activity, RNA...",0.269367,1.379299e-103
3,GO:0000976,transcription cis-regulatory region binding,0.257936,2.742129e-20
4,GO:0000977,RNA polymerase II transcription regulatory reg...,0.255101,3.198212e-25
5,GO:0003700,DNA-binding transcription factor activity,0.254886,4.249966e-40
6,GO:0001228,"DNA-binding transcription activator activity, ...",0.241213,1.316129e-32
7,GO:1990837,sequence-specific double-stranded DNA binding,0.235693,6.975437e-39
8,GO:0043565,sequence-specific DNA binding,0.200367,2.224132e-15
9,GO:0003712,transcription coregulator activity,0.196290,2.203983e-06
10,GO:0008013,beta-catenin binding,0.183156,4.068897e-06
11,GO:0003713,transcription coactivator activity,0.162575,2.359128e-08
12,GO:0061629,RNA polymerase II-specific DNA-binding transcr...,0.150804,4.068897e-06
13,GO:0003682,chromatin binding,0.142250,3.584962e-12
14,GO:0003729,mRNA binding,0.134359,7.262823e-06
15,GO:0003677,DNA binding,0.133476,1.006525e-18
16,GO:0140297,DNA-binding transcription factor binding,0.120978,1.140082e-03
17,GO:0042393,histone binding,0.100512,2.010536e-03
18,GO:0046872,metal ion binding,0.099368,2.071420e-21
19,GO:0003714,transcription corepressor activity,0.090153,5.488158e-03
20,GO:0005096,GTPase activator activity,0.067048,8.383891e-03
21,GO:0003723,RNA binding,0.066050,1.660925e-06
22,GO:0003779,actin binding,0.064111,1.578750e-02
23,GO:0042802,identical protein binding,-0.054372,9.666422e-06
24,GO:0042803,protein homodimerization activity,-0.077170,6.441276e-05
25,GO:0016887,ATP hydrolysis activity,-0.078300,6.853026e-05
26,GO:0005102,signaling receptor binding,-0.083235,1.140082e-03
27,GO:0038023,signaling receptor activity,-0.083397,1.279332e-02
28,GO:0005524,ATP binding,-0.087855,5.631595e-14
29,GO:0004222,metalloendopeptidase activity,-0.088839,1.579289e-02
30,GO:0061630,ubiquitin protein ligase activity,-0.092089,2.299499e-04
31,GO:0004842,ubiquitin-protein transferase activity,-0.116609,2.013996e-04
32,GO:0030246,carbohydrate binding,-0.118543,1.891665e-03
33,GO:0000287,magnesium ion binding,-0.137824,6.882420e-05
34,GO:0008083,growth factor activity,-0.158031,6.130115e-05
35,GO:0035401,histone H3Y41 kinase activity,-0.164925,7.297389e-07
36,GO:0140801,histone H2AXY142 kinase activity,-0.164925,7.297389e-07
37,GO:0008201,heparin binding,-0.196408,9.969619e-09
38,GO:0003924,GTPase activity,-0.217520,9.309600e-09
39,GO:0005178,integrin binding,-0.238417,1.585462e-12
40,GO:0004930,G protein-coupled receptor activity,-0.253768,7.210379e-23
41,GO:0005525,GTP binding,-0.257436,1.089850e-15

In [25]:
df_bio = pd.read_pickle('bioproc_significant.pkl')
df_bio_table = df_bio[['GO', 'effect_size', 'adj_pvalue']]
GO_names = []
for _, row in df_bio_table.iterrows():
    name = id_to_name[row['GO']]
    GO_names.append(name)
    
df_bio_table['Name'] = GO_names
df_bio_table = df_bio_table[['GO', 'Name', 'effect_size', 'adj_pvalue']]
df_bio_table.to_excel('BioProc.xlsx')
df_bio_table

/var/folders/1f/m8_t8g414dz2d33zlncf3gv40000gn/T/ipykernel_27406/974008585.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bio_table['Name'] = GO_names

,GO,Name,effect_size,adj_pvalue
0,GO:0006357,regulation of transcription by RNA polymerase II,0.258880,2.615363e-108
1,GO:0006325,chromatin organization,0.196093,2.060068e-06
2,GO:0000122,negative regulation of transcription by RNA po...,0.182531,1.515852e-31
3,GO:0045944,positive regulation of transcription by RNA po...,0.174721,3.161818e-35
4,GO:0000398,"mRNA splicing, via spliceosome",0.162386,2.146743e-05
5,GO:0007010,cytoskeleton organization,0.161775,5.730233e-05
6,GO:0045893,positive regulation of DNA-templated transcrip...,0.161634,3.434767e-18
7,GO:0009653,anatomical structure morphogenesis,0.160669,3.110812e-05
8,GO:0006355,regulation of DNA-templated transcription,0.160279,1.815844e-15
9,GO:0006366,transcription by RNA polymerase II,0.155319,1.937670e-06
10,GO:0008380,RNA splicing,0.145937,1.047953e-04
11,GO:0045892,negative regulation of DNA-templated transcrip...,0.127409,2.112965e-10
12,GO:0006338,chromatin remodeling,0.121771,3.110884e-05
13,GO:0006397,mRNA processing,0.101092,2.055100e-03
14,GO:0090090,negative regulation of canonical Wnt signaling...,0.099556,1.165361e-02
15,GO:0051056,regulation of small GTPase mediated signal tra...,0.098506,5.531593e-03
16,GO:0030036,actin cytoskeleton organization,0.090440,5.261552e-03
17,GO:0000226,microtubule cytoskeleton organization,0.078873,4.846945e-02
18,GO:0030154,cell differentiation,0.053792,8.184619e-03
19,GO:0009410,response to xenobiotic stimulus,-0.060269,4.345432e-02
20,GO:0007411,axon guidance,-0.062238,4.293900e-02
21,GO:0007268,chemical synaptic transmission,-0.062268,3.604667e-02
22,GO:0001525,angiogenesis,-0.066478,2.154297e-02
23,GO:0008284,positive regulation of cell population prolife...,-0.067320,2.045007e-03
24,GO:0007165,signal transduction,-0.067457,1.674057e-05
25,GO:0098609,cell-cell adhesion,-0.073222,2.144117e-02
26,GO:0016567,protein ubiquitination,-0.080182,1.146875e-03
27,GO:0007267,cell-cell signaling,-0.080656,1.521180e-02
28,GO:0007155,cell adhesion,-0.089705,3.934976e-05
29,GO:0001934,positive regulation of protein phosphorylation,-0.094319,2.279627e-02
30,GO:0051260,protein homooligomerization,-0.098342,1.288461e-02
31,GO:0002250,adaptive immune response,-0.099436,1.059546e-02
32,GO:0015031,protein transport,-0.100108,3.352509e-05
33,GO:0051649,establishment of localization in cell,-0.100256,1.050993e-02
34,GO:0030335,positive regulation of cell migration,-0.105074,4.182637e-04
35,GO:0030317,flagellated sperm motility,-0.113972,4.098019e-03
36,GO:0007166,cell surface receptor signaling pathway,-0.120464,4.946163e-05
37,GO:0030334,regulation of cell migration,-0.122848,5.209306e-03
38,GO:0051897,positive regulation of phosphatidylinositol 3-...,-0.127110,4.214485e-05
39,GO:0050821,protein stabilization,-0.133541,5.079220e-05
40,GO:0051607,defense response to virus,-0.133729,7.409770e-05
41,GO:0006508,proteolysis,-0.133750,1.228212e-09
42,GO:0006914,autophagy,-0.136388,4.831293e-04
43,GO:0007005,mitochondrion organization,-0.137644,8.880925e-04
44,GO:0031175,neuron projection development,-0.139589,4.352576e-04
45,GO:0043410,positive regulation of MAPK cascade,-0.140063,1.339810e-05
46,GO:0045087,innate immune response,-0.140349,8.920027e-09
47,GO:0043161,proteasome-mediated ubiquitin-dependent protei...,-0.156589,1.053311e-07
48,GO:0006886,intracellular protein transport,-0.158121,2.680881e-05
49,GO:0070374,positive regulation of ERK1 and ERK2 cascade,-0.160161,1.243296e-06
50,GO:0006954,inflammatory response,-0.161310,3.889119e-09
51,GO:0007189,adenylate cyclase-activating G protein-coupled...,-0.165565,2.269359e-05
52,GO:0007186,G protein-coupled receptor signaling pathway,-0.201759,5.085030e-17
53,GO:0007204,positive regulation of cytosolic calcium ion c...,-0.205588,5.759961e-07
54,GO:0007160,cell-matrix adhesion,-0.209485,2.060068e-06
55,GO:0006955,immune response,-0.232980,1.815844e-15